### ISSUE TITLE
D7 Database Mapping Tracking Issue

### ISSUE THREAD

**Issue by HybridEidolon** [HybridEidolon/makaikit#2]
- [x] act.dat
- [x] acteffect.dat
- [x] actfeature.dat
- [x] actlearn.dat
- [x] actmap.dat
- [x] ai.dat
- [x] aiparts.dat
- [x] anime.dat
- [x] animebank.dat
- [x] archive.dat
- [x] area.dat
- [x] battleflag.dat
- [x] bgm.dat
- [x] bu.dat
- [ ] calc.dat
- [ ] cellfeature.dat
- [x] characlass.dat - CharaClassData
- [x] character.dat
- [ ] charactersetting.dat
- [ ] charactersettingdebug.dat
- [x] charafeature.dat
- [ ] charaflag.dat
- [ ] charahelp.dat
- [x] charazukan.dat
- [x] cheatsetting.dat
- [ ] cmd.dat
- [ ] credit.dat
- [ ] debugconfig.dat
- [ ] debugtestconfig.dat
- [ ] demo.dat
- [ ] democharacter.dat
- [x] doping.dat
- [x] drink.dat
- [x] dungeon.dat
- [ ] ending.dat
- [ ] enemycreatetable.dat
- [ ] enemyparameterstable.dat
- [ ] eventcg.dat
- [ ] eventviewer.dat
- [x] evility.dat
- [ ] evility_capacity.dat
- [ ] featuretext.dat
- [ ] font.dat
- [ ] framebuffer.dat
- [ ] framework_anime.dat
- [ ] framework_animebank.dat
- [ ] framework_archive.dat
- [ ] framework_bgm.dat
- [ ] framework_calc.dat
- [ ] framework_cmd.dat
- [ ] framework_credit.dat
- [ ] framework_debugconfig.dat
- [ ] framework_font.dat
- [ ] framework_framebuffer.dat
- [ ] framework_gamedefine.dat
- [ ] framework_history.dat
- [ ] framework_icon.dat
- [ ] framework_model.dat
- [ ] framework_msg.dat
- [ ] framework_networkdefine.dat
- [ ] framework_number.dat
- [ ] framework_pad.dat
- [ ] framework_particle.dat
- [ ] framework_particlebank.dat
- [ ] framework_renderstep.dat
- [ ] framework_scripttype.dat
- [ ] framework_se.dat
- [ ] framework_shader.dat
- [ ] framework_string.dat
- [ ] framework_talkcommand.dat
- [ ] framework_texture.dat
- [ ] framework_trophy.dat
- [ ] framework_updatelevel.dat
- [ ] framework_vkey.dat
- [ ] framework_vkeycategory.dat
- [ ] framework_waterparam.dat
- [ ] framework_window.dat
- [ ] framework_zdefine.dat
- [ ] gamedefine.dat
- [ ] gameeffect.dat
- [ ] gameeffect_condition.dat
- [ ] gameeffect_effect.dat
- [ ] gameeffect_feature.dat
- [ ] gameeffect_value.dat
- [ ] gameflag.dat
- [ ] gamesetting.dat
- [ ] gamesettinglist.dat
- [ ] geoeffect.dat
- [ ] geopanel.dat
- [ ] group.dat
- [ ] history.dat
- [x] hospitalgacha.dat
- [ ] icon.dat
- [x] innocent.dat
- [x] innocentaffinity.dat
- [x] item.dat
- [x] itemcustom.dat
- [ ] itemeffect.dat
- [ ] itemeffecttable.dat
- [x] itemfeature.dat
- [ ] itemshoplineup.dat
- [x] itemstrengthen.dat
- [x] itemtype.dat
- [ ] itemworldlottery.dat
- [x] job.dat
- [ ] lotterytable.dat
- [ ] makaijingi.dat
- [ ] map.dat
- [ ] mapobject.dat
- [ ] model.dat
- [ ] modelinfo.dat
- [ ] modelsequence.dat
- [ ] modelsequencelist_record.dat
- [ ] modelsequencetype.dat
- [ ] msg.dat
- [ ] music.dat
- [ ] notice.dat
- [ ] number.dat
- [ ] pad.dat
- [ ] particle.dat
- [ ] particlebank.dat
- [ ] personality.dat
- [ ] placement_battle.dat
- [ ] placement_character.dat
- [ ] placement_town.dat
- [ ] quest.dat
- [ ] quest_type.dat
- [ ] randommap.dat
- [ ] randommap_area.dat
- [ ] randommap_areamask.dat
- [ ] randommap_light.dat
- [ ] randommap_material.dat
- [ ] randommap_object.dat
- [ ] randommap_posteffect.dat
- [ ] randomname.dat
- [ ] rankbattle.dat
- [ ] rankbattle_partysetting_debug.dat
- [ ] rankbattle_reward.dat
- [ ] rankbattle_testenemy.dat
- [ ] record_allrecord.dat
- [ ] record_networkrecord.dat
- [ ] renderstep.dat
- [ ] reward.dat
- [ ] rewardtable.dat
- [ ] saveicon.dat
- [ ] scripttype.dat
- [ ] se.dat
- [ ] senator.dat
- [ ] shader.dat
- [ ] shoprank.dat
- [ ] sounddefine.dat
- [x] stage.dat
- [ ] stagemission.dat
- [ ] stagemissionlist.dat
- [ ] stagemissionreward.dat
- [x] string.dat - StringData
- [ ] talk.dat
- [ ] talkcommand.dat
- [ ] talkdefine.dat
- [ ] talklist.dat
- [ ] texture.dat
- [ ] tournament.dat
- [ ] tournament_team.dat
- [ ] towntalklist.dat
- [ ] trophy.dat
- [ ] tsumeshogi.dat
- [ ] tsumeshogi_reward.dat
- [ ] tutorial.dat
- [ ] tutoriallist.dat
- [ ] updatelevel.dat
- [ ] victorycondition.dat
- [ ] vkey.dat
- [ ] vkeycategory.dat
- [ ] voice.dat
- [ ] voicetype.dat
- [ ] waterparam.dat
- [ ] weapontogether.dat
- [ ] window.dat
- [x] wish.dat
- [ ] zdefine.dat
